name        : solus-migrate
version     : 2
release     : 2
source     :
    - https://solus-project.com/sources/solus-migrate-2.tar.xz : 360676c8bcfb44fbe09a37db1ac3b1cb4224031fcd8dbfe0c386b679d90020f6
license     :
    - GPLv2+
summary     : Solus Migration Assistant - Reboot Required
description : |
    Solus Migration Assistant - Fixes "Evolve OS" strings, and repository.
install    : |
    mkdir -p $installdir/usr/lib/systemd/system/multi-user.target.wants
    install -D -m 0644 solus-migrate.service $installdir/usr/lib/systemd/system/solus-migrate.service
    install -D -m 0755 solus-migrate $installdir/usr/sbin/solus-migrate
    ln -sv /usr/lib/systemd/solus-migrate.service $installdir/usr/lib/systemd/system/multi-user.target.wants/.
